# Generated by Django 5.0 on 2026-01-18 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('post_type', models.CharField(choices=[('blog', 'Blog Post'), ('comparison', 'Product Comparison')], default='blog', max_length=50)),
                ('content', models.TextField(help_text='Markdown or HTML content of the post')),
                ('excerpt', models.CharField(blank=True, max_length=500)),
                ('author', models.CharField(default='The Full Price Team', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text='Show this post prominently')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Order to display products in the comparison')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_products', to='posts.post')),
            ],
            options={
                'ordering': ['post', 'order'],
                'unique_together': {('post', 'product')},
            },
        ),
    ]
