# Generated by Django 5.0 on 2026-01-18 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('greenhouse_gas_kg_per_kg', models.FloatField(default=0)),
                ('water_liters_per_kg', models.FloatField(default=0)),
                ('energy_kwh_per_kg', models.FloatField(default=0)),
                ('land_m2_per_kg', models.FloatField(default=0)),
                ('cost_per_kg', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('purchase_price_usd', models.FloatField(default=0, help_text='Price at purchase')),
                ('average_lifespan_years', models.FloatField(default=1, help_text='How long the product typically lasts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_grams', models.FloatField(help_text='Weight of this material in the product')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='products.product')),
            ],
            options={
                'ordering': ['product', 'material'],
                'unique_together': {('product', 'material')},
            },
        ),
    ]
