# Generated by Django 5.0 on 2026-01-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uses_per_lifespan',
            field=models.FloatField(default=1, help_text='How many times the product is used over its lifespan (e.g., 1 for single-use, 365 for daily use over 1 year)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_lifespan_years',
            field=models.FloatField(default=1, help_text='How long the product typically lasts in years'),
        ),
    ]
