# Generated by Django 5.0 on 2026-01-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_uses_per_lifespan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uses_per_lifespan',
        ),
        migrations.AddField(
            model_name='product',
            name='uses_per_year',
            field=models.FloatField(default=1, help_text='Average uses per year (e.g., 1 for single-use yearly, 365 for daily use)'),
        ),
    ]
