# Generated by Django 5.0 on 2026-01-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_uses_per_lifespan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_lifespan_years',
        ),
        migrations.AddField(
            model_name='product',
            name='average_lifespan_uses',
            field=models.FloatField(default=1, help_text='Average number of uses the product lasts before needing replacement (e.g., 1 for single-use, 500 for durable)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uses_per_year',
            field=models.FloatField(default=1, help_text='Average uses per year (e.g., 1 for yearly, 365 for daily use)'),
        ),
    ]
