# Generated by Django 5.0 on 2026-02-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_lifecycle_phases'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='end_of_life_source',
            field=models.TextField(blank=True, help_text='Source citation for end of life phase data'),
        ),
        migrations.AddField(
            model_name='material',
            name='methodology',
            field=models.TextField(blank=True, help_text='General methodology notes'),
        ),
        migrations.AddField(
            model_name='material',
            name='production_source',
            field=models.TextField(blank=True, help_text='Source citation for production phase data'),
        ),
        migrations.AddField(
            model_name='material',
            name='transport_source',
            field=models.TextField(blank=True, help_text='Source citation for transport phase data'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_phase_source',
            field=models.TextField(blank=True, help_text='Source citation for use phase data'),
        ),
    ]
