# Generated by Django 5.0 on 2026-02-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_material_end_of_life_source_material_methodology_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='end_of_life_source',
        ),
        migrations.RemoveField(
            model_name='material',
            name='production_source',
        ),
        migrations.RemoveField(
            model_name='material',
            name='transport_source',
        ),
        migrations.RemoveField(
            model_name='product',
            name='use_phase_source',
        ),
        migrations.AddField(
            model_name='material',
            name='end_of_life_source_name',
            field=models.CharField(blank=True, help_text='Name of the source', max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='end_of_life_source_note',
            field=models.TextField(blank=True, help_text='Notes about the end of life source or calculation'),
        ),
        migrations.AddField(
            model_name='material',
            name='end_of_life_source_url',
            field=models.URLField(blank=True, help_text='Link to end of life data source'),
        ),
        migrations.AddField(
            model_name='material',
            name='production_source_name',
            field=models.CharField(blank=True, help_text="Name of the source (e.g. 'EPA 2021')", max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='production_source_note',
            field=models.TextField(blank=True, help_text='Notes about the production source or calculation'),
        ),
        migrations.AddField(
            model_name='material',
            name='production_source_url',
            field=models.URLField(blank=True, help_text='Link to production data source'),
        ),
        migrations.AddField(
            model_name='material',
            name='transport_source_name',
            field=models.CharField(blank=True, help_text='Name of the source', max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='transport_source_note',
            field=models.TextField(blank=True, help_text='Notes about the transport source or calculation'),
        ),
        migrations.AddField(
            model_name='material',
            name='transport_source_url',
            field=models.URLField(blank=True, help_text='Link to transport data source'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_phase_source_name',
            field=models.CharField(blank=True, help_text='Name of the source', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='use_phase_source_note',
            field=models.TextField(blank=True, help_text='Notes about the use phase source or calculation'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_phase_source_url',
            field=models.URLField(blank=True, help_text='Link to use phase data source'),
        ),
    ]
