# Generated by Django 5.0 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_material_end_of_life_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exposed_assumptions',
            field=models.JSONField(blank=True, default=list, help_text='Backend-managed editable assumptions shown in the frontend. Leave empty to use defaults.'),
        ),
    ]
