# Generated by Django 5.0 on 2026-03-16

from django.db import migrations, models
import django.db.models.deletion


def migrate_exposed_assumptions_to_relational(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Assumption = apps.get_model('products', 'Assumption')
    AssumptionOption = apps.get_model('products', 'AssumptionOption')

    default_phase = 'use'
    default_metric = 'greenhouse_gas_kg'

    for product in Product.objects.all():
        assumptions = getattr(product, 'exposed_assumptions', None) or []
        if not isinstance(assumptions, list):
            continue

        for index, assumption_data in enumerate(assumptions):
            if not isinstance(assumption_data, dict):
                continue

            options = assumption_data.get('options') or []
            phase = default_phase
            metric = default_metric

            for option in options:
                phase_multipliers = option.get('phase_multipliers') if isinstance(option, dict) else None
                if not isinstance(phase_multipliers, dict):
                    continue
                for phase_key, metric_map in phase_multipliers.items():
                    if isinstance(metric_map, dict) and metric_map:
                        phase = phase_key
                        metric = next(iter(metric_map.keys()))
                        break
                if phase != default_phase or metric != default_metric:
                    break

            assumption = Assumption.objects.create(
                product_id=product.id,
                key=assumption_data.get('key') or f"assumption_{index + 1}",
                label=assumption_data.get('label') or f"Assumption {index + 1}",
                description=assumption_data.get('description', ''),
                phase=phase,
                metric=metric,
                input_type=assumption_data.get('input_type') or 'select',
                exposed=True,
                default_option_key=assumption_data.get('default_option_id', ''),
                sort_order=index,
            )

            for option_index, option in enumerate(options):
                if not isinstance(option, dict):
                    continue

                option_key = option.get('id') or f"option_{option_index + 1}"
                option_label = option.get('label') or option_key

                multiplier = 1.0
                phase_multipliers = option.get('phase_multipliers') or {}
                if isinstance(phase_multipliers, dict):
                    metric_map = phase_multipliers.get(phase, {})
                    if isinstance(metric_map, dict):
                        multiplier = float(metric_map.get(metric, 1.0))

                AssumptionOption.objects.create(
                    assumption_id=assumption.id,
                    option_key=option_key,
                    label=option_label,
                    multiplier=multiplier,
                    is_default=(option_key == assumption.default_option_key),
                    sort_order=option_index,
                )


def reverse_migration(apps, schema_editor):
    # No-op reverse conversion to avoid rehydrating removed JSON shape.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_exposed_assumptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('phase', models.CharField(choices=[('production', 'Production'), ('transport', 'Transport'), ('end_of_life', 'End of Life'), ('use', 'Use')], max_length=30)),
                ('metric', models.CharField(choices=[('greenhouse_gas_kg', 'Greenhouse Gas (kg CO₂e)'), ('water_liters', 'Water (liters)'), ('energy_kwh', 'Energy (kWh)'), ('land_m2', 'Land (m²)'), ('cost_usd', 'Cost (USD)')], max_length=40)),
                ('input_type', models.CharField(choices=[('select', 'Select')], default='select', max_length=20)),
                ('exposed', models.BooleanField(default=False)),
                ('default_option_key', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assumptions', to='products.material')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assumptions', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssumptionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('multiplier', models.FloatField(default=1.0)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('assumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.assumption')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('assumption', 'option_key')},
            },
        ),
        migrations.RunPython(migrate_exposed_assumptions_to_relational, reverse_migration),
        migrations.RemoveField(
            model_name='product',
            name='exposed_assumptions',
        ),
    ]
