# Generated by Django 5.0 on 2026-03-16 21:51

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def populate_material_slugs(apps, schema_editor):
    """Backfill slug for existing Material rows."""
    Material = apps.get_model('products', 'Material')
    for mat in Material.objects.all():
        mat.slug = slugify(mat.name)
        mat.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_multi_metric_global_assumptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description of this material family.')),
                ('typical_products', models.TextField(blank=True, help_text='Comma-separated list of typical product types (e.g. "bottles, packaging, food containers").')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Material categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='end_of_life_info',
            field=models.TextField(blank=True, help_text='Recycling, composting, landfill characteristics.'),
        ),
        migrations.AddField(
            model_name='material',
            name='environmental_notes',
            field=models.TextField(blank=True, help_text='Additional sustainability / toxicity / ecological notes.'),
        ),
        migrations.AddField(
            model_name='material',
            name='fabrication_info',
            field=models.TextField(blank=True, help_text='How the raw material is processed into usable form.'),
        ),
        # Step 1: add slug WITHOUT unique constraint
        migrations.AddField(
            model_name='material',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, default=''),
            preserve_default=False,
        ),
        # Step 2: backfill slugs
        migrations.RunPython(populate_material_slugs, migrations.RunPython.noop),
        # Step 3: now apply unique
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='material',
            name='sourcing_info',
            field=models.TextField(blank=True, help_text='How this material is sourced / extracted (e.g. mined, harvested, synthesized).'),
        ),
        migrations.AlterField(
            model_name='assumptioneffect',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Broad material family (e.g. "Commodity plastics").', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='products.materialcategory'),
        ),
    ]
